# Seminar 2. Vectorization

## TF-IDF

Term frequency, $\text{tf}(t,d)$, is the relative frequency of term $t$ within document $d$,

$$
\text{tf}(t,d)=\frac{f_{t,d}}{\sum_{t' \in d}f_{t',d}},
$$

where $f_{t,d}$ is the raw count of a term in a document, i.e., the number of times that term $t$ occurs in document $d$. Note the denominator is simply the total number of terms in document $d$ (counting each occurrence of the same term separately).

The inverse document frequency is a measure of how much information the word provides, i.e., how common or rare it is across all documents. It is the logarithmically scaled inverse fraction of the documents that contain the word (obtained by dividing the total number of documents by the number of documents containing the term, and then taking the logarithm of that quotient):

$$
\text{idf}(t,D)=\log{\frac{N}{n_t}}
$$

with
- $D$: is the set of all documents in the corpus
- $N=|D|$: total number of documents in the corpus
- $n_t=|\{d \in D:t \in d\}|$: number of documents where the term $t$ appears (i.e., $\text{tf}(t,d) \neq 0$. If the term is not in the corpus, this will lead to a division-by-zero. It is therefore common to adjust the numerator to $1+N$ and the denominator to $1+|\{d \in D:t \in d\}|$.

Then tf–idf is calculated as

$$
\text{tfidf}(t,d,D)=\text{tf}(t,d)*\text{idf}(t,D)
$$

### Low-level implementation

In [1]:
import math
from collections import Counter
from typing import Dict, List

documents = [
    "cat dog bird",
    "cat rat cheese rat",
    "dog cat friend human"
]

Step 1. Tokenization

In [2]:
tokenized_docs = [doc.split() for doc in documents]
print("Tokenized docs:", tokenized_docs)

Tokenized docs: [['cat', 'dog', 'bird'], ['cat', 'rat', 'cheese', 'rat'], ['dog', 'cat', 'friend', 'human']]

Step 2. Count TF

Task 1. Given the formula, write function for counting TF.

$\text{tf}(t,d)=\frac{f_{t,d}}{\sum_{t' \in d}f_{t',d}},$

where $f_{t,d}$ is the raw count of a term in a document, i.e., the number of times that term $t$ occurs in document $d$. Note the denominator is simply the total number of terms in document $d$ (counting each occurrence of the same term separately).

In [3]:
def compute_tf(tokens: List[str]) -> Dict[str,float]:
    """Count TF for tokens in one document."""
    freq = {}

    for token in tokens:
        if token not in freq.keys():
            freq[token] = 1
        else:
            freq[token] += 1

    tf = {}

    for key, value in freq.items():
        tf[key] = value/len(tokens)

    return tf

In [4]:
tf_doc0 = compute_tf(tokenized_docs[0])
print("\nTF for document:", tf_doc0)

TF for document: {'cat': 0.3333333333333333, 'dog': 0.3333333333333333, 'bird': 0.3333333333333333}

Step 3. Count IDF

Task 2. Given the formula, write function for counting IDF.

$\text{idf}(t,D)=\log{\frac{N}{n_t}}$

with
- $D$: is the set of all documents in the corpus
- $N=|D|$: total number of documents in the corpus
- $n_t=|\{d \in D:t \in d\}|$: number of documents where the term $t$ appears (i.e., $\text{tf}(t,d) \neq 0$. If the term is not in the corpus, this will lead to a division-by-zero. It is therefore common to adjust the numerator to $1+N$ and the denominator to $1+|\{d \in D:t \in d\}|$.

In [5]:
def compute_idf(tokenized_docs:List[List[str]]) -> Dict[str,float]:
    """Count IDF for all tokens in corpus."""
    num_docs = len(tokenized_docs)
    # Step 1. For each term count the number of documents in which it occurs
    freq = {}
    for doc in tokenized_docs:
        unique_terms = set(doc)
        for term in unique_terms:
            freq[term] = freq.get(term, 0) + 1
    # Step 2. Count IDF
    idf = {term: math.log((num_docs + 1) / (1 + df)) for term, df in freq.items()}
    return idf

In [6]:
idf_dict = compute_idf(tokenized_docs)
print("\nIDF for all tokens:", idf_dict)

IDF for all tokens: {'bird': 0.6931471805599453, 'cat': 0.0, 'dog': 0.28768207245178085, 'rat': 0.6931471805599453, 'cheese': 0.6931471805599453, 'friend': 0.6931471805599453, 'human': 0.6931471805599453}

Step 4. Count TF-IDF

In [7]:
tfidf_doc0 = {term: tf_doc0.get(term, 0) * idf_dict.get(term, 0) for term in tf_doc0.keys()}
print("\nTF-IDF for document 0:", tfidf_doc0)

TF-IDF for document 0: {'cat': 0.0, 'dog': 0.09589402415059362, 'bird': 0.23104906018664842}

Step 5. Vectors

Task 3.

Create a matrix of size $n \times m$ where $n$ is the number of documents and $m$ is the number of unique terms.

In [8]:
import pandas as pd

In [9]:
# @title Try to write your own code in the cell above or check the implementation in this cell

# create corpus vocabulary (in this example I decided to preserve the order of terms' appearance.
# If the order is not relevant, it would be easier to use `set`.)
vocab = []
tf = []
for doc in tokenized_docs:
    for token in doc:
        if token not in vocab:
            vocab.append(token)
    # Count TF for each doc
    tf.append(compute_tf(doc))
tfidf = [{term: tf_doc.get(term, 0) * idf_dict.get(term, 0) for term in vocab} for tf_doc in tf]
pd.DataFrame(tfidf, columns=vocab)

   cat       dog      bird       rat    cheese    friend     human
0  0.0  0.095894  0.231049  0.000000  0.000000  0.000000  0.000000
1  0.0  0.000000  0.000000  0.346574  0.173287  0.000000  0.000000
2  0.0  0.071921  0.000000  0.000000  0.000000  0.173287  0.173287

### TF-IDF Vectorizer

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [11]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)
pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

       bird       cat    cheese       dog    friend     human      rat
0  0.720333  0.425441  0.000000  0.547832  0.000000  0.000000  0.00000
1  0.000000  0.255374  0.432385  0.000000  0.000000  0.000000  0.86477
2  0.000000  0.345205  0.000000  0.444514  0.584483  0.584483  0.00000

In [12]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (3, 7)>

## Word2Vec

In [13]:
%pip install gensim -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 34.9 MB/s eta 0:00:00

### Using pretrained model

In [14]:
import gensim.downloader as api

In [15]:
w2v_model = api.load('word2vec-ruscorpora-300')

word = "жизнь_NOUN"
if word in w2v_model.key_to_index:
    print(f"Word: '{word}':\n", w2v_model[word])
    print(f"\nVector size: {w2v_model[word].shape}")
else:
    print(f"Word '{word}' is not present in the model.")

[==================================================] 100.0% 198.8/198.8MB downloaded
Word: 'жизнь_NOUN':
 [-0.12112214  0.00870241  0.03419324  0.00739663  0.0498926   0.08822373
 -0.01143234  0.01909082  0.05713632 -0.09353109 -0.0659969  -0.0309724
 -0.030187    0.02126888 -0.00516937 -0.01718024 -0.01184916 -0.03552986
  0.00953155  0.00170796  0.06193599  0.02846407 -0.16981365  0.07623787
 -0.02958078 -0.07465961  0.01444931  0.015319   -0.00151932  0.02656073
  0.0556897   0.08897429  0.02000033 -0.01548212  0.11891276 -0.02439923
  0.07700787 -0.0455139  -0.0203667  -0.05561786  0.00300816  0.07009368
  0.02917391 -0.00023318 -0.02388291  0.07162231  0.05349505 -0.08117097
  0.14713782 -0.06134159  0.01559311 -0.02290069  0.04617056 -0.03017698
 -0.04739884  0.01343922 -0.10965177 -0.03340828  0.00238579  0.07266998
  0.04936632  0.07298899  0.03146793 -0.00565133 -0.03581524 -0.02989143
 -0.04947808 -0.05474768 -0.00945385 -0.03948738 -0.02623238 -0.05858833
  0.01024302 -0.1280483  -0.06203976 -0.01413697 -0.04647967 -0.02582693
 -0.01232981 -0.04074922  0.01244622 -0.06056328 -0.07832362  0.0511266
 -0.10398304 -0.07021355 -0.04041968  0.00218554 -0.01253509 -0.0150812
 -0.07269018  0.03235578 -0.05788642  0.03369694  0.00872385  0.02969898
  0.04700826  0.07137492  0.02079728  0.03091928  0.01716538 -0.03840522
 -0.01264555  0.02444975  0.07722754 -0.05436717  0.01159565 -0.02822903
  0.01864375 -0.02616121  0.00843591 -0.02408047 -0.12473228 -0.07619746
 -0.02693015  0.03895037 -0.04445096  0.05942155  0.04313974 -0.07497489
  0.03735914 -0.06415938  0.05727303  0.01476461  0.0207279  -0.05713515
 -0.09309825  0.10340548 -0.01840457  0.05807883 -0.11082378 -0.0195812
 -0.09719124  0.10859749 -0.05712273 -0.00748184 -0.05124804  0.14168014
  0.00283737 -0.01486408  0.02971046 -0.09183735  0.07449784 -0.01889947
 -0.01160387  0.02428757 -0.09489934 -0.01865233  0.15177271 -0.00056986
 -0.05579229  0.00997391  0.01133149 -0.06566311 -0.05121834  0.13424514
 -0.00098091  0.06966271 -0.0347321   0.00110232 -0.0163012   0.04632746
 -0.15165749 -0.11021329  0.0421449  -0.01189026 -0.0504494  -0.05000357
 -0.13618277  0.01104044  0.14199324 -0.03282246 -0.05917643 -0.00743017
  0.088572    0.06378558  0.04219943  0.08350445 -0.00941982  0.06600982
  0.05065092 -0.04386322 -0.02882884 -0.10741693 -0.01266634 -0.04489675
  0.09769817 -0.00257172 -0.04964245  0.02268819  0.08597254 -0.1013632
 -0.02526265 -0.02064505  0.03001533  0.07870118 -0.04027663 -0.03154327
  0.02897172 -0.06998548  0.00904406  0.01244583 -0.00522663 -0.0375653
 -0.0216101   0.00738862 -0.06164512  0.02374304 -0.01729083  0.11406939
  0.02779718 -0.00425449  0.0471653  -0.06660122  0.06820117 -0.04102973
  0.05340959 -0.02884437  0.02285053  0.03580327 -0.00643078 -0.00217627
  0.02812595 -0.07108013 -0.05790703 -0.02634582  0.03871137  0.0120404
 -0.0827372   0.07658078 -0.03919473  0.02158619  0.05232695  0.06439871
 -0.08934961 -0.07074325 -0.10917491  0.01698606 -0.04143837 -0.02625396
  0.01622949  0.01656309 -0.01104529  0.05650615 -0.11158913  0.06914792
 -0.00211066  0.07238014 -0.06955675 -0.08441037 -0.03437777 -0.11141424
  0.01435251 -0.0225221   0.03619625 -0.10625314 -0.02273607  0.04141008
  0.04808879  0.02995712 -0.00545024  0.03372022 -0.03977463 -0.06290047
 -0.07433575  0.09453961 -0.04908576  0.07676757 -0.0744471   0.03242106
  0.00926582  0.01022081  0.05894539  0.1665365   0.06885935  0.00973874
  0.07482019  0.01837143  0.012482   -0.00775395 -0.05900463 -0.0297311
  0.03442881 -0.02999843  0.00889496 -0.01102148 -0.10385118 -0.09663808
  0.00216601  0.0683158   0.01101386 -0.05499766 -0.0004586   0.02395842
  0.01252335 -0.01148354  0.02055411  0.06800751 -0.01828278  0.02821895]

Vector size: (300,)

In [25]:
w2v_model.key_to_index

{'весь_DET': 0,
 'человек_NOUN': 1,
 'мочь_VERB': 2,
 'год_NOUN': 3,
 'сказать_VERB': 4,
 'время_NOUN': 5,
 'говорить_VERB': 6,
 'становиться_VERB': 7,
 'знать_VERB': 8,
 'самый_DET': 9,
 'дело_NOUN': 10,
 'день_NOUN': 11,
 'жизнь_NOUN': 12,
 'рука_NOUN': 13,
 'очень_ADV': 14,
 'первый_ADJ': 15,
 'давать_VERB': 16,
 'новый_ADJ': 17,
 'слово_NOUN': 18,
 'иметь_VERB': 19,
 'большой_ADJ': 20,
 'идти_VERB': 21,
 'глаз_NOUN': 22,
 'место_NOUN': 23,
 'лицо_NOUN': 24,
 'видеть_VERB': 25,
 'хотеть_VERB': 26,
 'понимать_VERB': 27,
 'должный_ADJ': 28,
 'работа_NOUN': 29,
 'каждый_DET': 30,
 'друг_NOUN': 31,
 'голова_NOUN': 32,
 'дом_NOUN': 33,
 'оставаться_VERB': 34,
 'сторона_NOUN': 35,
 'начинать_VERB': 36,
 'думать_VERB': 37,
 'хорошо_ADV': 38,
 'жить_VERB': 39,
 'стоять_VERB': 40,
 'спрашивать_VERB': 41,
 'сделать_VERB': 42,
 'выходить_VERB': 43,
 'последний_ADJ': 44,
 'русский_ADJ': 45,
 'сила_NOUN': 46,
 'получать_VERB': 47,
 'какой-то_DET': 48,
 'хороший_ADJ': 49,
 'случай_NOUN': 50,
 'вопрос_NOUN': 51,
 'отвечать_VERB': 52,
 'россия_NOUN': 53,
 'несколько_NUM': 54,
 'мир_NOUN': 55,
 'город_NOUN': 56,
 'делать_VERB': 57,
 'пойти_VERB': 58,
 'приходить_VERB': 59,
 'земля_NOUN': 60,
 'принимать_VERB': 61,
 'часть_NOUN': 62,
 'вид_NOUN': 63,
 'ребенок_NOUN': 64,
 'конец_NOUN': 65,
 'взять_VERB': 66,
 'всякий_DET': 67,
 'находить_VERB': 68,
 'высокий_ADJ': 69,
 'сидеть_VERB': 70,
 'что-то_PRON': 71,
 'отец_NOUN': 72,
 'оказываться_VERB': 73,
 'вода_NOUN': 74,
 'смотреть_VERB': 75,
 'москва_NOUN': 76,
 'час_NOUN': 77,
 'являться_VERB': 78,
 'народ_NOUN': 79,
 'любить_VERB': 80,
 'проходить_VERB': 81,
 'никто_PRON': 82,
 'образ_NOUN': 83,
 'казаться_VERB': 84,
 'женщина_NOUN': 85,
 'бог_NOUN': 86,
 'нога_NOUN': 87,
 'страна_NOUN': 88,
 'голос_NOUN': 89,
 'писать_VERB': 90,
 'ночь_NOUN': 91,
 'душа_NOUN': 92,
 'старый_ADJ': 93,
 'лишь_PART': 94,
 'также_ADV': 95,
 'общий_ADJ': 96,
 'называть_VERB': 97,
 'молодой_ADJ': 98,
 'отношение_NOUN': 99,
 'великий_ADJ': 100,
 'уходить_VERB': 101,
 'деньги_NOUN': 102,
 'второй_ADJ': 103,
 'мысль_NOUN': 104,
 'приходиться_VERB': 105,
 'работать_VERB': 106,
 'именно_PART': 107,
 'оно_PRON': 108,
 'дорога_NOUN': 109,
 'рассказывать_VERB': 110,
 'увидеть_VERB': 111,
 'дверь_NOUN': 112,
 'вместе_ADV': 113,
 'представлять_VERB': 114,
 'просто_PART': 115,
 'война_NOUN': 116,
 'находиться_VERB': 117,
 'происходить_VERB': 118,
 'книга_NOUN': 119,
 'некоторый_DET': 120,
 'свет_NOUN': 121,
 'минута_NOUN': 122,
 'полный_ADJ': 123,
 'скоро_ADV': 124,
 'вечер_NOUN': 125,
 'письмо_NOUN': 126,
 'главный_ADJ': 127,
 'показывать_VERB': 128,
 'стол_NOUN': 129,
 'жена_NOUN': 130,
 'далеко_ADV': 131,
 'мать_NOUN': 132,
 'никакой_DET': 133,
 'решать_VERB': 134,
 'путь_NOUN': 135,
 'входить_VERB': 136,
 'комната_NOUN': 137,
 'имя_NOUN': 138,
 'считать_VERB': 139,
 'история_NOUN': 140,
 'белый_ADJ': 141,
 'замечать_VERB': 142,
 'сегодня_ADV': 143,
 'совершенно_ADV': 144,
 'маленький_ADJ': 145,
 'нужно_ADV': 146,
 'пора_NOUN': 147,
 'власть_NOUN': 148,
 'сердце_NOUN': 149,
 'часто_ADV': 150,
 'черный_ADJ': 151,
 'узнавать_VERB': 152,
 'число_NOUN': 153,
 'сын_NOUN': 154,
 'право_NOUN': 155,
 'кроме_ADP': 156,
 'сразу_ADV': 157,
 'разный_ADJ': 158,
 'система_NOUN': 159,
 'против_ADP': 160,
 'утро_NOUN': 161,
 'лежать_VERB': 162,
 'оставлять_VERB': 163,
 'общество_NOUN': 164,
 'любовь_NOUN': 165,
 'вообще_ADV': 166,
 'улица_NOUN': 167,
 'приезжать_VERB': 168,
 'начало_NOUN': 169,
 'мало_ADV': 170,
 'настоящий_ADJ': 171,
 'смерть_NOUN': 172,
 'особенно_ADV': 173,
 'тысяча_NOUN': 174,
 'снова_ADV': 175,
 'положение_NOUN': 176,
 'продолжать_VERB': 177,
 'написать_VERB': 178,
 'язык_NOUN': 179,
 'читать_VERB': 180,
 'советский_ADJ': 181,
 'многий_DET': 182,
 'возможность_NOUN': 183,
 'закон_NOUN': 184,
 'ходить_VERB': 185,
 'подходить_VERB': 186,
 'князь_NOUN': 187,
 'машина_NOUN': 188,
 'ко_ADP': 189,
 'иной_DET': 190,
 'среди_ADP': 191,
 'появляться_VERB': 192,
 'ждать_VERB': 193,
 'оба_NUM': 194,
 'целый_ADJ': 195,
 'бывать_VERB': 196,
 'окно_NOUN': 197,
 'российский_ADJ': 198,
 'чувство_NOUN': 199,
 'поэтому_ADV': 200,
 'мера_NOUN': 201,
 'например_ADV': 202,
 'брат_NOUN': 203,
 'известный_ADJ': 204,
 'помнить_VERB': 205,
 'форма_NOUN': 206,
 'долго_ADV': 207,
 'красный_ADJ': 208,
 'просить_VERB': 209,
 'месяц_NOUN': 210,
 'нужный_ADJ': 211,
 'быстро_ADV': 212,
 'живой_ADJ': 213,
 'приводить_VERB': 214,
 'садиться_VERB': 215,
 'взгляд_NOUN': 216,
 'действие_NOUN': 217,
 'условие_NOUN': 218,
 'военный_ADJ': 219,
 'труд_NOUN': 220,
 'собственный_ADJ': 221,
 'следовать_VERB': 222,
 'открывать_VERB': 223,
 'товарищ_NOUN': 224,
 'около_ADP': 225,
 'начинаться_VERB': 226,
 'затем_ADV': 227,
 'цель_NOUN': 228,
 'движение_NOUN': 229,
 'разговор_NOUN': 230,
 'внимание_NOUN': 231,
 'государственный_ADJ': 232,
 'подумать_VERB': 233,
 'забывать_VERB': 234,
 'чувствовать_VERB': 235,
 'предлагать_VERB': 236,
 'тело_NOUN': 237,
 'назад_ADV': 238,
 'помогать_VERB': 239,
 'составлять_VERB': 240,
 'стена_NOUN': 241,
 'проводить_VERB': 242,
 'позволять_VERB': 243,
 'играть_VERB': 244,
 'пять_NUM': 245,
 'огромный_ADJ': 246,
 'посмотреть_VERB': 247,
 'развитие_NOUN': 248,
 'суд_NOUN': 249,
 'группа_NOUN': 250,
 'состояние_NOUN': 251,
 'умирать_VERB': 252,
 'следующий_ADJ': 253,
 'вести_VERB': 254,
 'поставлять_VERB': 255,
 'средство_NOUN': 256,
 'вернуться_VERB': 257,
 'слышать_VERB': 258,
 'полагать_VERB': 259,
 'создавать_VERB': 260,
 'результат_NOUN': 261,
 'важный_ADJ': 262,
 'давно_ADV': 263,
 'третий_ADJ': 264,
 'собираться_VERB': 265,
 'помощь_NOUN': 266,
 'армия_NOUN': 267,
 'берег_NOUN': 268,
 'вызывать_VERB': 269,
 'муж_NOUN': 270,
 'наука_NOUN': 271,
 'лес_NOUN': 272,
 'школа_NOUN': 273,
 'подымать_VERB': 274,
 'связь_NOUN': 275,
 'порядок_NOUN': 276,
 'речь_NOUN': 277,
 'рано_ADV': 278,
 'вещь_NOUN': 279,
 'решение_NOUN': 280,
 'бояться_VERB': 281,
 'церковь_NOUN': 282,
 'смысл_NOUN': 283,
 'область_NOUN': 284,
 'век_NOUN': 285,
 'московский_ADJ': 286,
 'совет_NOUN': 287,
 'действительно_ADV': 288,
 'двор_NOUN': 289,
 'государство_NOUN': 290,
 'сильный_ADJ': 291,
 'все-таки_PART': 292,
 'ехать_VERB': 293,
 'ответ_NOUN': 294,
 'глядеть_VERB': 295,
 'хотеться_VERB': 296,
 'иван_NOUN': 297,
 'правительство_NOUN': 298,
 'из-за_ADP': 299,
 'спать_VERB': 300,
 'старик_NOUN': 301,
 'театр_NOUN': 302,
 'вставать_VERB': 303,
 'останавливаться_VERB': 304,
 'четыре_NUM': 305,
 'заниматься_VERB': 306,
 'ряд_NOUN': 307,
 'обращаться_VERB': 308,
 'слушать_VERB': 309,
 'бросать_VERB': 310,
 'процесс_NOUN': 311,
 'значит_ADV': 312,
 'занимать_VERB': 313,
 'причина_NOUN': 314,
 'проблема_NOUN': 315,
 'правда_ADV': 316,
 'довольно_ADV': 317,
 'добрый_ADJ': 318,
 'отдавать_VERB': 319,
 'статья_NOUN': 320,
 'кто-то_PRON': 321,
 'встречать_VERB': 322,
 'плечо_NOUN': 323,
 'го_NOUN': 324,
 'подниматься_VERB': 325,
 'дух_NOUN': 326,
 'подобный_ADJ': 327,
 'рядом_ADV': 328,
 'должно_ADV': 329,
 'убивать_VERB': 330,
 'попадать_VERB': 331,
 'воздух_NOUN': 332,
 'партия_NOUN': 333,
 'море_NOUN': 334,
 'слишком_ADV': 335,
 'рубль_NOUN': 336,
 'простой_ADJ': 337,
 'любой_DET': 338,
 'семья_NOUN': 339,
 'квартира_NOUN': 340,
 'легко_ADV': 341,
 'готовый_ADJ': 342,
 'господин_NOUN': 343,
 'роль_NOUN': 344,
 'момент_NOUN': 345,
 'успевать_VERB': 346,
 'деятельность_NOUN': 347,
 'политический_ADJ': 348,
 'задача_NOUN': 349,
 'равный_ADJ': 350,
 'человеческий_ADJ': 351,
 'шаг_NOUN': 352,
 'член_NOUN': 353,
 'газета_NOUN': 354,
 'организация_NOUN': 355,
 'близкий_ADJ': 356,
 'солнце_NOUN': 357,
 'приносить_VERB': 358,
 'качество_NOUN': 359,
 'требовать_VERB': 360,
 'небо_NOUN': 361,
 'александр_NOUN': 362,
 'поле_NOUN': 363,
 'весьма_ADV': 364,
 'как-то_ADV': 365,
 'улыбаться_VERB': 366,
 'борьба_NOUN': 367,
 'искать_VERB': 368,
 'идея_NOUN': 369,
 'неделя_NOUN': 370,
 'существовать_VERB': 371,
 'река_NOUN': 372,
 'девушка_NOUN': 373,
 'удаваться_VERB': 374,
 'случаться_VERB': 375,
 'снимать_VERB': 376,
 'объяснять_VERB': 377,
 'род_NOUN': 378,
 'особый_ADJ': 379,
 'основной_ADJ': 380,
 'генерал_NOUN': 381,
 'крупный_ADJ': 382,
 'брать_VERB': 383,
 'тяжелый_ADJ': 384,
 'войско_NOUN': 385,
 'точно_ADV': 386,
 'вполне_ADV': 387,
 'компания_NOUN': 388,
 'петр_NOUN': 389,
 'какой-нибудь_DET': 390,
 'небольшой_ADJ': 391,
 'мнение_NOUN': 392,
 'мама_NOUN': 393,
 'солдат_NOUN': 394,
 'ум_NOUN': 395,
 'стараться_VERB': 396,
 'держать_VERB': 397,
 'служба_NOUN': 398,
 'гора_NOUN': 399,
 'вера_NOUN': 400,
 'искусство_NOUN': 401,
 'характер_NOUN': 402,
 'сильно_ADV': 403,
 'начальник_NOUN': 404,
 'внутренний_ADJ': 405,
 'гость_NOUN': 406,
 'служить_VERB': 407,
 'производить_VERB': 408,
 'лошадь_NOUN': 409,
 'картина_NOUN': 410,
 'посылать_VERB': 411,
 'опыт_NOUN': 412,
 'интерес_NOUN': 413,
 'природа_NOUN': 414,
 'автор_NOUN': 415,
 'значение_NOUN': 416,
 'верить_VERB': 417,
 'желать_VERB': 418,
 'огонь_NOUN': 419,
 'деревня_NOUN': 420,
 'ибо_CCONJ': 421,
 'правый_ADJ': 422,
 'словно_CCONJ': 423,
 'офицер_NOUN': 424,
 'кровь_NOUN': 425,
 'длинный_ADJ': 426,
 'план_NOUN': 427,
 'палец_NOUN': 428,
 'малый_ADJ': 429,
 'менее_ADV': 430,
 'широкий_ADJ': 431,
 'николай_NOUN': 432,
 'хозяин_NOUN': 433,
 'угол_NOUN': 434,
 'пить_VERB': 435,
 'страшный_ADJ': 436,
 'судьба_NOUN': 437,
 'сообщать_VERB': 438,
 'пол_NOUN': 439,
 'десять_NUM': 440,
 'точка_NOUN': 441,
 'сколько_ADV': 442,
 'прямо_PART': 443,
 'возникать_VERB': 444,
 'государь_NOUN': 445,
 'воля_NOUN': 446,
 'кажется_ADV': 447,
 'относиться_VERB': 448,
 'вспомнить_VERB': 449,
 'дерево_NOUN': 450,
 'трудно_ADV': 451,
 'ход_NOUN': 452,
 'мальчик_NOUN': 453,
 'показываться_VERB': 454,
 'царь_NOUN': 455,
 'видно_ADV': 456,
 'заставлять_VERB': 457,
 'течение_NOUN': 458,
 'бежать_VERB': 459,
 'центр_NOUN': 460,
 'переходить_VERB': 461,
 'современный_ADJ': 462,
 'материал_NOUN': 463,
 'передавать_VERB': 464,
 'мужчина_NOUN': 465,
 'глава_NOUN': 466,
 'туда_ADV': 467,
 'петербург_NOUN': 468,
 'необходимый_ADJ': 469,
 'дочь_NOUN': 470,
 'счастие_NOUN': 471,
 'количество_NOUN': 472,
 'поехать_VERB': 473,
 'прекрасный_ADJ': 474,
 'пусть_PART': 475,
 'народный_ADJ': 476,
 'темный_ADJ': 477,
 'уезжать_VERB': 478,
 'указывать_VERB': 479,
 'тихо_ADV': 480,
 'край_NOUN': 481,
 'ветер_NOUN': 482,
 'подавать_VERB': 483,
 'уровень_NOUN': 484,
 'класс_NOUN': 485,
 'правило_NOUN': 486,
 'вместо_ADP': 487,
 'событие_NOUN': 488,
 'уметь_VERB': 489,
 'состоять_VERB': 490,
 'немного_ADV': 491,
 'похожий_ADJ': 492,
 'встречаться_VERB': 493,
 'едва_ADV': 494,
 'единственный_ADJ': 495,
 'бывший_ADJ': 496,
 'поздно_ADV': 497,
 'домой_ADV': 498,
 'возвращаться_VERB': 499,
 'завод_NOUN': 500,
 'направление_NOUN': 501,
 'повторять_VERB': 502,
 'странный_ADJ': 503,
 'общественный_ADJ': 504,
 'чистый_ADJ': 505,
 'бумага_NOUN': 506,
 'плохо_ADV': 507,
 'кричать_VERB': 508,
 'память_NOUN': 509,
 'различный_ADJ': 510,
 'сначала_ADV': 511,
 'свобода_NOUN': 512,
 'андрей_NOUN': 513,
 'надежда_NOUN': 514,
 'предмет_NOUN': 515,
 'производство_NOUN': 516,
 'получаться_VERB': 517,
 'управление_NOUN': 518,
 'несмотря_ADV': 519,
 'данный_ADJ': 520,
 'цена_NOUN': 521,
 'пример_NOUN': 522,
 'двадцать_NUM': 523,
 'стоить_VERB': 524,
 'соглашаться_VERB': 525,
 'сюда_ADV': 526,
 'определять_VERB': 527,
 'счет_NOUN': 528,
 'пытаться_VERB': 529,
 'собирать_VERB': 530,
 'вчера_ADV': 531,
 'отдельный_ADJ': 532,
 'касаться_VERB': 533,
 'вовсе_ADV': 534,
 'толпа_NOUN': 535,
 'половина_NOUN': 536,
 'сон_NOUN': 537,
 'союз_NOUN': 538,
 'губа_NOUN': 539,
 'хлеб_NOUN': 540,
 'чужой_ADJ': 541,
 'обращать_VERB': 542,
 'выступать_VERB': 543,
 'стих_NOUN': 544,
 'спина_NOUN': 545,
 'культура_NOUN': 546,
 'революция_NOUN': 547,
 'местный_ADJ': 548,
 'желание_NOUN': 549,
 'встреча_NOUN': 550,
 'состав_NOUN': 551,
 'что-нибудь_PRON': 552,
 'сад_NOUN': 553,
 'устраивать_VERB': 554,
 'граница_NOUN': 555,
 'грудь_NOUN': 556,
 'степень_NOUN': 557,
 'прочитывать_VERB': 558,
 'вперед_ADV': 559,
 'министр_NOUN': 560,
 'мужик_NOUN': 561,
 'писатель_NOUN': 562,
 'участие_NOUN': 563,
 'глубокий_ADJ': 564,
 'программа_NOUN': 565,
 'произносить_VERB': 566,
 'сестра_NOUN': 567,
 'успех_NOUN': 568,
 'красивый_ADJ': 569,
 'радость_NOUN': 570,
 'прежде_ADP': 571,
 'камень_NOUN': 572,
 'ученый_NOUN': 573,
 'девочка_NOUN': 574,
 'факт_NOUN': 575,
 'рост_NOUN': 576,
 'сознание_NOUN': 577,
 'прежний_ADJ': 578,
 'страх_NOUN': 579,
 'институт_NOUN': 580,
 'доктор_NOUN': 581,
 'сергей_NOUN': 582,
 'орган_NOUN': 583,
 'масса_NOUN': 584,
 'очередь_NOUN': 585,
 'дорогой_ADJ': 586,
 'достаточно_ADV': 587,
 'отказываться_VERB': 588,
 'иванович_NOUN': 589,
 'чай_NOUN': 590,
 'игра_NOUN': 591,
 'рассказ_NOUN': 592,
 'отправляться_VERB': 593,
 'столько_NUM': 594,
 'волос_NOUN': 595,
 'личный_ADJ': 596,
 'поступать_VERB': 597,
 'ожидать_VERB': 598,
 'однажды_ADV': 599,
 'район_NOUN': 600,
 'действовать_VERB': 601,
 'милый_ADJ': 602,
 'зал_NOUN': 603,
 'песня_NOUN': 604,
 'журнал_NOUN': 605,
 'купить_VERB': 606,
 'несколько_ADV': 607,
 'основа_NOUN': 608,
 'герой_NOUN': 609,
 'святой_ADJ': 610,
 'столь_ADV': 611,
 'сцена_NOUN': 612,
 'признавать_VERB': 613,
 'французский_ADJ': 614,
 'предприятие_NOUN': 615,
 'больший_ADJ': 616,
 'круг_NOUN': 617,
 'период_NOUN': 618,
 'литература_NOUN': 619,
 'нос_NOUN': 620,
 'снег_NOUN': 621,
 'слеза_NOUN': 622,
 'завтра_ADV': 623,
 'поэт_NOUN': 624,
 'напоминать_VERB': 625,
 'смочь_VERB': 626,
 'рынок_NOUN': 627,
 'враг_NOUN': 628,
 'ухо_NOUN': 629,
 'правда_NOUN': 630,
 'серьезный_ADJ': 631,
 'вокруг_ADP': 632,
 'немой_ADJ': 633,
 'полк_NOUN': 634,
 'связывать_VERB': 635,
 'основание_NOUN': 636,
 'большинство_NOUN': 637,
 'способ_NOUN': 638,
 'близко_ADV': 639,
 'исследование_NOUN': 640,
 'собака_NOUN': 641,
 'лето_NOUN': 642,
 'достигать_VERB': 643,
 'проект_NOUN': 644,
 'знакомый_ADJ': 645,
 'использовать_VERB': 646,
 'ясно_ADV': 647,
 'дома_ADV': 648,
 'представитель_NOUN': 649,
 'художник_NOUN': 650,
 'доходить_VERB': 651,
 'средний_ADJ': 652,
 'свободный_ADJ': 653,
 'плохой_ADJ': 654,
 'болезнь_NOUN': 655,
 'линия_NOUN': 656,
 'рабочий_ADJ': 657,
 'президент_NOUN': 658,
 'бой_NOUN': 659,
 'научный_ADJ': 660,
 'немец_NOUN': 661,
 'заявлять_VERB': 662,
 'выражение_NOUN': 663,
 'крайний_ADJ': 664,
 'явление_NOUN': 665,
 'врач_NOUN': 666,
 'образование_NOUN': 667,
 'остальной_DET': 668,
 'старший_ADJ': 669,
 'повод_NOUN': 670,
 'население_NOUN': 671,
 'известно_ADV': 672,
 'объявлять_VERB': 673,
 'золотой_ADJ': 674,
 'роман_NOUN': 675,
 'впечатление_NOUN': 676,
 'тип_NOUN': 677,
 'рабочий_NOUN': 678,
 'принадлежать_VERB': 679,
 'исчезать_VERB': 680,
 'владимир_NOUN': 681,
 'слава_NOUN': 682,
 'влияние_NOUN': 683,
 'молчать_VERB': 684,
 'собрание_NOUN': 685,
 'закрывать_VERB': 686,
 'интересный_ADJ': 687,
 'срок_NOUN': 688,
 'устанавливать_VERB': 689,
 'рот_NOUN': 690,
 'обстоятельство_NOUN': 691,
 'отмечать_VERB': 692,
 'кабинет_NOUN': 693,
 'возможный_ADJ': 694,
 'немецкий_ADJ': 695,
 'фронт_NOUN': 696,
 'удар_NOUN': 697,
 'политика_NOUN': 698,
 'переставать_VERB': 699,
 'внешний_ADJ': 700,
 'ситуация_NOUN': 701,
 'номер_NOUN': 702,
 'выбирать_VERB': 703,
 'либо_CCONJ': 704,
 'тема_NOUN': 705,
 'граф_NOUN': 706,
 'легкий_ADJ': 707,
 'петь_VERB': 708,
 'божий_ADJ': 709,
 'музыка_NOUN': 710,
 'откуда_ADV': 711,
 'обычный_ADJ': 712,
 'услышать_VERB': 713,
 'исторический_ADJ': 714,
 'директор_NOUN': 715,
 'европа_NOUN': 716,
 'тонкий_ADJ': 717,
 'пользоваться_VERB': 718,
 'бросаться_VERB': 719,
 'прежде_ADV': 720,
 'корабль_NOUN': 721,
 'холодный_ADJ': 722,
 'надеяться_VERB': 723,
 'детский_ADJ': 724,
 'знание_NOUN': 725,
 'зеленый_ADJ': 726,
 'содержание_NOUN': 727,
 'бедный_ADJ': 728,
 'дядя_NOUN': 729,
 'наверное_ADV': 730,
 'наиболее_ADV': 731,
 'сие_PRON': 732,
 'социальный_ADJ': 733,
 'размер_NOUN': 734,
 'мелкий_ADJ': 735,
 'прощать_VERB': 736,
 'причем_CCONJ': 737,
 'прошлый_ADJ': 738,
 'мировой_ADJ': 739,
 'лист_NOUN': 740,
 'документ_NOUN': 741,
 'звать_VERB': 742,
 'площадь_NOUN': 743,
 'бить_VERB': 744,
 'вероятно_ADV': 745,
 'командир_NOUN': 746,
 'смеяться_VERB': 747,
 'понятие_NOUN': 748,
 'приказывать_VERB': 749,
 'городской_ADJ': 750,
 'крестьянин_NOUN': 751,
 'существо_NOUN': 752,
 'пустой_ADJ': 753,
 'шесть_NUM': 754,
 'высоко_ADV': 755,
 'счастливый_ADJ': 756,
 'короткий_ADJ': 757,
 'принцип_NOUN': 758,
 'железный_ADJ': 759,
 'обед_NOUN': 760,
 'утверждать_VERB': 761,
 'будущее_NOUN': 762,
 'звук_NOUN': 763,
 'возможно_ADV': 764,
 'название_NOUN': 765,
 'ставить_VERB': 766,
 'зуб_NOUN': 767,
 'павел_NOUN': 768,
 'представление_NOUN': 769,
 'экономический_ADJ': 770,
 'удовольствие_NOUN': 771,
 'потерять_VERB': 772,
 'создание_NOUN': 773,
 'национальный_ADJ': 774,
 'данные_NOUN': 775,
 'цвет_NOUN': 776,
 'гораздо_ADV': 777,
 'медленно_ADV': 778,
 'учитель_NOUN': 779,
 'метод_NOUN': 780,
 'станция_NOUN': 781,
 'капитан_NOUN': 782,
 'богатый_ADJ': 783,
 'необходимо_ADV': 784,
 'требование_NOUN': 785,
 'сквозь_ADP': 786,
 'родитель_NOUN': 787,
 'ребята_NOUN': 788,
 'вскоре_ADV': 789,
 'левый_ADJ': 790,
 'древний_ADJ': 791,
 'способный_ADJ': 792,
 'носить_VERB': 793,
 'миллион_NOUN': 794,
 'веселый_ADJ': 795,
 'духовный_ADJ': 796,
 'низкий_ADJ': 797,
 'серый_ADJ': 798,
 'прямой_ADJ': 799,
 'родной_ADJ': 800,
 'выполнять_VERB': 801,
 'спокойно_ADV': 802,
 'рассматривать_VERB': 803,
 'наступать_VERB': 804,
 'команда_NOUN': 805,
 'глубина_NOUN': 806,
 'американский_ADJ': 807,
 'недавно_ADV': 808,
 'единый_ADJ': 809,
 'многие_PRON': 810,
 'хозяйство_NOUN': 811,
 'определенный_ADJ': 812,
 'исполнять_VERB': 813,
 'вновь_ADV': 814,
 'остров_NOUN': 815,
 'ссср_NOUN': 816,
 'цветок_NOUN': 817,
 'гражданин_NOUN': 818,
 'информация_NOUN': 819,
 'выход_NOUN': 820,
 'знаменитый_ADJ': 821,
 'зима_NOUN': 822,
 'выпивать_VERB': 823,
 'никак_ADV': 824,
 'обнаруживать_VERB': 825,
 'улыбка_NOUN': 826,
 'плакать_VERB': 827,
 'решаться_VERB': 828,
 'ах_INTJ': 829,
 'профессор_NOUN': 830,
 'папа_NOUN': 831,
 'назначать_VERB': 832,
 'изменение_NOUN': 833,
 'взглядывать_VERB': 834,
 'приглашать_VERB': 835,
 'впервые_ADV': 836,
 'зрение_NOUN': 837,
 'победа_NOUN': 838,
 'председатель_NOUN': 839,
 'продавать_VERB': 840,
 'называться_VERB': 841,
 'ради_ADP': 842,
 'колено_NOUN': 843,
 'расти_VERB': 844,
 'элемент_NOUN': 845,
 'честь_NOUN': 846,
 'доказывать_VERB': 847,
 'множество_NOUN': 848,
 'почувствовать_VERB': 849,
 'пространство_NOUN': 850,
 'противник_NOUN': 851,
 'кончаться_VERB': 852,
 'король_NOUN': 853,
 'совершать_VERB': 854,
 'необходимость_NOUN': 855,
 'английский_ADJ': 856,
 'михаил_NOUN': 857,
 'зато_CCONJ': 858,
 'ложиться_VERB': 859,
 'нравиться_VERB': 860,
 'польза_NOUN': 861,
 'обычно_ADV': 862,
 'значительный_ADJ': 863,
 'тотчас_ADV': 864,
 'комитет_NOUN': 865,
 'сложный_ADJ': 866,
 'предложение_NOUN': 867,
 'анна_NOUN': 868,
 'карман_NOUN': 869,
 'алексей_NOUN': 870,
 'особенность_NOUN': 871,
 'сохранять_VERB': 872,
 'слабый_ADJ': 873,
 'сто_NUM': 874,
 'приниматься_VERB': 875,
 'пара_NOUN': 876,
 'здание_NOUN': 877,
 'дама_NOUN': 878,
 'упасть_VERB': 879,
 'читатель_NOUN': 880,
 'кстати_ADV': 881,
 'среда_NOUN': 882,
 'звезда_NOUN': 883,
 'спасать_VERB': 884,
 'студент_NOUN': 885,
 'василий_NOUN': 886,
 'участок_NOUN': 887,
 'доставать_VERB': 888,
 'оружие_NOUN': 889,
 'телефон_NOUN': 890,
 'вспоминать_VERB': 891,
 'личность_NOUN': 892,
 'умный_ADJ': 893,
 'черта_NOUN': 894,
 'прийти_VERB': 895,
 'тихий_ADJ': 896,
 'волна_NOUN': 897,
 'дальнейший_ADJ': 898,
 'поскольку_CCONJ': 899,
 'отправлять_VERB': 900,
 'долгий_ADJ': 901,
 'учиться_VERB': 902,
 'постоянно_ADV': 903,
 'допускать_VERB': 904,
 'ясный_ADJ': 905,
 'позиция_NOUN': 906,
 'нести_VERB': 907,
 'ворота_NOUN': 908,
 'предполагать_VERB': 909,
 'сколько_CCONJ': 910,
 'удивляться_VERB': 911,
 'выражать_VERB': 912,
 'очевидно_ADV': 913,
 'боевой_ADJ': 914,
 'сталин_NOUN': 915,
 'отсутствие_NOUN': 916,
 'верный_ADJ': 917,
 'праздник_NOUN': 918,
 'фигура_NOUN': 919,
 'иметься_VERB': 920,
 'парень_NOUN': 921,
 'ужас_NOUN': 922,
 'специальный_ADJ': 923,
 'фильм_NOUN': 924,
 'самолет_NOUN': 925,
 'поддерживать_VERB': 926,
 'предел_NOUN': 927,
 'обеспечивать_VERB': 928,
 'десяток_NOUN': 929,
 'птица_NOUN': 930,

### Training Your Own Model

In [17]:
import re

import nltk
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from tqdm.auto import tqdm

In [18]:
lemmatizer = WordNetLemmatizer()
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

Dataset: https://www.google.com/url?q=https%3A%2F%2Fwww.kaggle.com%2Fdatasets%2Fteam-ai%2Fspam-text-message-classification%2F

In [19]:
df = pd.read_csv('SPAM.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [20]:
stop_words = set(stopwords.words('english'))

def remove_stop_words_and_lemm(text):
    word_tokens = word_tokenize(text)
    filtered_text = [lemmatizer.lemmatize(w) for w in word_tokens
                         if not w.lower() in stop_words]

    res_text = ' '.join(filtered_text)
    return res_text

In [21]:
def manual_clear(text):
    filtered_tokens = re.findall(r'[a-z]{2,}', text.lower())
    return ' '.join(filtered_tokens)

In [22]:
tqdm.pandas()

df['Message'] = df['Message'].progress_apply(remove_stop_words_and_lemm)
df['Message'] = df['Message'].progress_apply(manual_clear)
df

  0%|          | 0/5572 [00:00<?, ?it/s]

  0%|          | 0/5572 [00:00<?, ?it/s]

     Category                                            Message
0         ham  go jurong point crazy available bugis great wo...
1         ham                              ok lar joking wif oni
2        spam  free entry wkly comp win fa cup final tkts st ...
3         ham                      dun say early hor already say
4         ham                nah think go usf life around though
...       ...                                                ...
5567     spam  nd time tried contact pound prize claim easy c...
5568      ham                            going esplanade fr home
5569      ham                               pity mood suggestion
5570      ham  guy bitching acted like interested buying some...
5571      ham                                     rofl true name

[5572 rows x 2 columns]

In [23]:
all_words = []

df['Message'].apply(lambda x : all_words.extend(x.split()))

word_count = Counter(all_words)
word_count.most_common(20)

[('call', 627),
 ('get', 408),
 ('ur', 391),
 ('gt', 318),
 ('lt', 316),
 ('go', 315),
 ('ok', 293),
 ('free', 288),
 ('day', 281),
 ('know', 270),
 ('ll', 260),
 ('come', 254),
 ('got', 253),
 ('like', 250),
 ('good', 248),
 ('time', 246),
 ('text', 220),
 ('love', 218),
 ('want', 217),
 ('send', 200)]

Word2Vec (https://radimrehurek.com/gensim/models/word2vec.html)

**Parameters:**

- `sentences`: List of sentences as list of token lists.
- `vector_size`: Dimensionality of the embedding vectors (default: 100).
- `min_count`: Minimum word frequency to include in vocabulary.
- `window`: Maximum distance between current and predicted word.
- `workers`: Number of training threads.
- `sg`: 1 for Skip-gram, 0 for CBOW.
- `alpha`: Initial learning rate.
- `epochs`: Number of training epochs (formerly `iter`)

**Methods:**
- `build_vocab()`: Builds vocabulary from data.
- `train()`: Trains the model on sentences.
- `save()` and `load()`: Saves/loads model to/from file.
- `wv.most_similar(positive, negative)`: Finds similar words (wv is KeyedVectors).
- `wv.similarity(word1, word2)`: Computes cosine similarity between words.
- `init_sims(replace=True)`: Optimizes memory by replacing full vectors with normalized ones.

In [26]:
w2v = Word2Vec(sentences=df['Message'].apply(lambda x: x.split()), vector_size=25, min_count=1, seed=42)

In [27]:
w2v.wv['go']

array([-0.1487324 , -1.845588  , -0.39797267, -0.5477892 , -0.3390987 ,
       -0.14104205, -0.30209732,  0.519727  , -0.7741899 ,  0.19019245,
       -0.88524234,  0.6142445 , -3.0399122 ,  1.623625  ,  0.89616275,
       -0.44633138,  1.0452987 , -0.15708973, -1.7137464 ,  1.1436971 ,
       -0.2969176 ,  0.6815132 ,  0.87539905,  1.1577687 ,  0.04455895],
      dtype=float32)

## GloVe

In [28]:
import gensim.downloader as gs
import numpy as np

glove = gs.load('glove-twitter-25')

[==================================================] 100.0% 104.8/104.8MB downloaded

In [29]:
glove['cat'].shape

(25,)

Example:

Generating a vector representation of text given word embeddings. Simple realisation by counting a mean vector.

In [30]:
embedding_size = glove['cat'].shape[0]

embedding_df = pd.DataFrame([], columns=[f'emb {i}' for i in range(embedding_size)])
# iterate over all texts in dataframe
for _, row in tqdm(df.iterrows(), total=len(df)):
    text = row['Message'].split()
    # fill text matrix with vectors of words occuring in it
    emb_matrix = []
    for word in text:
        try:
            emb_word = glove[word]
        except KeyError:
            continue
            # emb_word = [0 for _ in range(embedding_size)]
        emb_matrix.append(emb_word)
    # count mean value of vectors
    avg_emb = np.mean(np.array(emb_matrix), axis=0)
    embedding_df.loc[len(embedding_df)] = avg_emb

embedding_df

  0%|          | 0/5572 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/tmp/ipython-input-2376919162.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  embedding_df.loc[len(embedding_df)] = avg_emb

,emb 0,emb 1,emb 2,emb 3,emb 4,emb 5,emb 6,emb 7,emb 8,emb 9,...,emb 15,emb 16,emb 17,emb 18,emb 19,emb 20,emb 21,emb 22,emb 23,emb 24
0,-0.282485,0.317474,0.138595,-0.348058,-0.320595,0.107828,0.517043,0.159260,0.214994,-0.169675,...,0.171143,0.350759,-0.187526,-0.463635,0.249159,-0.126669,-0.327796,-0.040991,-0.007411,0.278105
1,-0.074996,0.266892,0.377192,-0.093010,-0.574472,-0.316744,-0.152268,0.160230,-0.142340,0.508098,...,0.264926,0.432370,-0.453696,-0.614064,0.074778,0.647006,0.059942,-0.299348,0.554856,-0.174234
2,0.012178,0.739647,-0.221913,-0.508841,0.002910,-0.407856,0.367755,-0.195612,0.186368,-0.058700,...,0.050187,0.359159,-0.495891,-0.495704,-0.246067,-0.608734,-0.467419,0.232789,0.260451,-0.538218
3,0.099361,0.733045,0.247028,-0.363987,-0.398553,-0.295712,0.847007,-0.074347,-0.265625,0.556066,...,0.096179,0.773530,-0.474530,-0.524087,-0.391853,0.365488,0.558595,-0.065398,0.725585,-0.149877
4,-0.007623,0.479504,0.149703,-0.343417,-0.658401,0.211070,1.123219,-0.199515,-0.148649,0.264348,...,0.060943,0.190455,-0.837893,-0.054137,-0.162433,0.147304,0.218516,0.199540,0.072663,-0.110319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.031726,0.728328,-0.210128,-0.190231,0.133793,-0.178479,0.623080,-0.264422,0.198138,0.080553,...,0.116530,0.291762,-0.420273,-0.482406,-0.301040,-0.267808,-0.084908,0.131469,0.103317,-0.429246
5568,-0.773277,0.724000,0.337388,-0.592416,-0.587138,0.017886,0.561440,-0.614535,0.477569,-0.042852,...,-0.136764,0.208797,-0.434453,-0.630858,-0.084565,-0.121637,-0.488671,0.229452,-0.143308,0.355256
5569,-0.035332,0.344687,-0.387425,0.424747,0.197467,0.356627,1.029587,-0.285986,0.040730,-0.135903,...,0.897503,0.744410,-0.654943,0.148100,-0.282578,0.113610,0.248770,-0.389524,0.578293,-0.680167
5570,-0.153924,0.728202,0.301370,-0.260191,0.005104,0.087682,1.049221,-0.696766,-0.450446,-0.100667,...,0.249873,0.374357,-0.558181,-0.158728,-0.398227,0.131614,-0.069433,-0.096306,0.003980,-0.516132
5571,0.364697,-0.137806,0.158010,-0.007566,0.005250,-0.603210,1.390967,0.143813,-0.589259,0.009572,...,0.153976,0.693180,0.040733,-0.153950,0.249367,0.692320,0.471343,-0.138717,0.267134,-0.501111

## FastText

In [31]:
from gensim.models import FastText

In [32]:
ft = FastText(sentences=df['Message'].apply(lambda x: x.split()), vector_size=25, window=5, min_count=1, workers=4, sg=1)

In [33]:
ft.wv['go']

array([ 0.05359192, -0.31778795,  0.8045535 , -0.00190616,  0.0262356 ,
       -0.8853365 , -0.04508992, -0.59447765, -0.9335927 , -0.08067333,
       -0.75733036, -0.4262235 ,  1.232389  , -1.0482275 , -0.11514448,
       -0.10229486,  0.40140843,  0.2121043 ,  0.12901366, -0.04674616,
       -0.24006923,  0.18314236,  0.2627432 , -0.12990817, -0.6758618 ],
      dtype=float32)

## Checking Vectors Quality

### 1. Similarity

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
print(f"{cosine_similarity([w2v.wv['go'] + w2v.wv['fast']], [w2v.wv['run']])[0][0]: .3f}")

 0.995

In [36]:
print(f"{cosine_similarity([glove['go'] + glove['fast']], [glove['run']])[0][0]: .3f}")

 0.937

In [37]:
print(f"{cosine_similarity([ft.wv['go'] + ft.wv['fast']], [ft.wv['run']])[0][0]: .3f}")

 0.993

### 2. Visual

In [38]:
from sklearn.decomposition import PCA
import plotly.express as px

#### W2V

In [39]:
vocab = w2v.wv.index_to_key
X = w2v.wv[vocab]

In [40]:
pca = PCA(2, random_state=42)
X_transformed = pca.fit_transform(X)

In [47]:
vecs_df = pd.DataFrame(X_transformed, index=vocab, columns=['x', 'y'])

fig = px.scatter(vecs_df, x='x', y='y', hover_name=vecs_df.index, width=800, height=400)
fig.show()

#### GloVe

Unfortunately, I had to remove the output of the following cell as there are just too many vectors and building an interactive representation of them makes file too heavy so it exceeds GitHub file size limit.

In [ ]:
vocab = glove.index_to_key
X = glove[vocab]
pca = PCA(2, random_state=42)
X_transformed = pca.fit_transform(X)
vecs_df = pd.DataFrame(X_transformed, index=vocab, columns=['x', 'y'])

fig = px.scatter(vecs_df, x='x', y='y', hover_name=vecs_df.index, width=800, height=400)
fig.show()

#### FastText

In [50]:
vocab = ft.wv.index_to_key
X = ft.wv[vocab]
pca = PCA(2, random_state=42)
X_transformed = pca.fit_transform(X)
vecs_df = pd.DataFrame(X_transformed, index=vocab, columns=['x', 'y'])

fig = px.scatter(vecs_df, x='x', y='y', hover_name=vecs_df.index, width=800, height=400)
fig.show()

## Additional sources:
1. https://lena-voita.github.io/nlp_course/word_embeddings.html
2. https://habr.com/ru/articles/778048/
3. https://neerc.ifmo.ru/wiki/index.php?title=%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D1%81%D0%BB%D0%BE%D0%B2